const mongoose = require("mongoose");
const Schema = mongoose.Schema;
const passportLocalMongoose = require("passport-local-mongoose");

const userSchema = new Schema({
  //username and password are automatically generated by passportLocalMongoose
  email: {
    type: String,
    required: true,
  },
});

//Adds authentication functionality to Mongoose schema :-
//1. Adds Fields (username and password)
//2. Hashes & Salts Passwords
//3. Adds Methods (register(), authenticate(), serializeUser())
//4. Simplifies Authentication
userSchema.plugin(passportLocalMongoose);

module.exports = mongoose.model("User", userSchema);
